### ISSUE TITLE
latimes-state-totals.csv hasn't updated since 9/02/21

### ISSUE THREAD

**Issue by bretburns01** [datadesk/california-coronavirus-data#34]

**Comment by palewire** [comment]
Yes, we've switched to using the state's totals, away from an independent county survey. We did a close comparison of the two methods and found that the state's tally is now at pace with the counties. In some areas, it's actually better now due to county reporting systems slowing down. The result is that we can give our readers better data with less work by switching. The state data files are now included in this repo and update daily.
