### ISSUE TITLE
latimes-county-totals.csv retired?

### ISSUE THREAD

**Issue by jeremydratcliff** [datadesk/california-coronavirus-data#35]
Hello,

I note that the latimes-county-totals.csv hasn't been updated since September 2. Has this file been retired?

**Comment by palewire** [comment]
Yes, we've switched to using the state's totals, away from an independent county survey. We did a close comparison of the two methods and found that the state's tally is now at pace with the counties. In some areas, it's actually better now due to county reporting systems slowing down. The result is that we can give our readers better data with less work by switching. The state data files are now included in this repo and update daily.
